const types = {
	GET_USER: 'GET_USER',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_FAILURE: 'GET_USER_FAILURE',
	GET_USER_LOGOUT: 'GET_USER_LOGOUT',
	SIGN_UP_USER: 'SIGN_UP_USER',
};

export default types;
